### ISSUE TITLE
退出视频仍然在播放。

### ISSUE THREAD

**Issue by Thereisnospon** [CoXier/Girl#2]
开始界面的笑脸变形了。还是本来就这样。。
为什么点开了视频，退出后还在播放，仍然有声音。。

**Comment by CoXier** [comment]
首页的那个变形，其实是因为Activity里面的笑脸位置和之前的背景里面的笑脸的位置有点微小差距，具体的你看看代码。我会尽快修复。另一个问题，我还没有遇到过...你是用的新版本吗？

**Comment by CoXier** [comment]
@Thereisnospon  已经解决变形的问题，请查看
